#pragma once

// AUTO-GENERATED by CMake configure_file — do not edit.
// To change the version, update project(... VERSION X.Y.Z) in CMakeLists.txt.
namespace bridge::version
{
inline constexpr const char* kAppVersion = "2.6.5";
}
